### ISSUE TITLE
Crash while trying to decode base64

### ISSUE THREAD

**Issue by ondra-novak** [ermouth/couch-photon#33]
```
general.js:28 Form Sys.JSON.Base64 failed to initialize. Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded. Error: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at Object.base642blob (http://localhost:5984/photon/_design/photon/lib/general.js:29:6697)
    at Object.init (http://localhost:5984/photon/_design/photon/photon.js:13:21317)
    at H (http://localhost:5984/photon/_design/photon/lib/general.js:28:12808)
    at s (http://localhost:5984/photon/_design/photon/lib/general.js:28:17644)
    at g (http://localhost:5984/photon/_design/photon/lib/general.js:28:15019)
    at e.fn.init.K (http://localhost:5984/photon/_design/photon/lib/general.js:28:20114)
    at .my-form-list (http://localhost:5984/photon/_design/photon/lib/general.js:28:28430)
    at http://localhost:5984/photon/_design/photon/lib/general.js:14:12286
    at A (http://localhost:5984/photon/_design/photon/lib/general.js:28:9529)
    at y (http://localhost:5984/photon/_design/photon/lib/general.js:28:18492)
```

Failed document

```
{
	"_id": "i.1lpbm9JXNqnpfkMxGuYS",
	"_rev": "2-09d128a1e8e307d2d5674172972de785",
	"amount": 0.0009892523487,
	"bot": "bot.1lpb7gJXNppqusMl7Rtj",
	"invoice_text": "lnbc989240n1psthnt4pp5rrn77szydquarttc34cq3hgyxa6ws9dnskjhm8zqwy9vrn7d5uxssp56pntqz59d7wjwj2wv2z37ytwe686ffxan5sl0euarrajxlq6kq6sdzzd4kkymm59e68yctyv5sxjmnkda5kxefqyvckcurzd5u55kzww9h8qentf4uywa2e2vcqzynxqrrss9qxpq9qsqrzjqwryaup9lh50kkranzgcdnn2fgvx390wgj5jd07rwr3vxeje0glc7zn0agqqr7cqqqqqqqlgqqqqqeqqjqtz9qwryaup9lh50kkranzgcdnn2fgvx390wgj5jd07rwr3vxeje0glc7qqqq05qqqqqvsqfq04w5evzgkty8jwn8vphp0vc6gnu9gjw3ct877sawd0ra5varuru46tt4a8z8mer59m4gh3fwvn02ktlrqjvphcz08n5s5etglavydusqhf8ztz",
	"ln": true,
	"owner": "1jEEgB1SgHtdxoRVFqIy",
	"paid_time": 31104000000,
	"req_time": 1622920565604,
	"request_id": "18e7ef40446839d1ad788d7008dd043774e815b385a57d9c40710ac1cfcda70d"
}
```

Possible issue:  the script is trying to decode invoice_text, which is not in base64 format (it is Bitcoin Lightning Invoice, which is encoded in bech32 format)

Possible fix: pack into try-catch block.

**Comment by ermouth** [comment]
Interestingly it had try/catch block already but its yield was never used. Good point, as usual.
